#!/usr/bin/env python3
"""Embed checked, pinned public definitions from an explicit Foundation checkout."""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess
import sys

p = argparse.ArgumentParser(description=__doc__)
p.add_argument("foundation", type=Path)
p.add_argument("--check", action="store_true")
a = p.parse_args()
source = a.foundation.resolve()
sys.path.insert(0, str(source / "services/library/src"))
from prim_library.library import Library
from prim_library.host_catalog import export_host_catalog

commit = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=source, text=True).strip()
catalog = export_host_catalog(Library(), commit)
data = (json.dumps(catalog, ensure_ascii=True, indent=2) + "\n").encode()
digest = hashlib.sha256(data).hexdigest()
encoded = base64.b64encode(data).decode()
swift = ('// Generated by scripts/sync-prim-library.py; data only. Do not hand edit.\n'
         f'// Foundation source: {commit}\n'
         'enum PrimLibraryBundled {\n'
         f'    static let sha256 = "{digest}"\n'
         f'    static let base64 = "{encoded}"\n'
         '}\n')
target = Path(__file__).resolve().parents[1] / "Sources/PrimsPasteCore/PrimLibraryBundled.swift"
if a.check:
    if not target.exists() or target.read_text() != swift:
        p.error("Bundled Library drift; regenerate from the recorded Foundation commit.")
else:
    target.write_text(swift)
print(json.dumps({"profiles": len(catalog["kits"]), "source_commit": commit, "catalog_sha256": digest}))
